apiVersion: v2
name: weacast-arpege-isobaric-europe-loader
description: A Krawler based service to download ARPEGE europe forecast data
version: 1.0.1
appVersion: isobaric-europe-1.11.0
home: https://github.com/weacast/weacast-loader
annotations:
  category: WeacastLoader
keywords:
  - Meteo France
  - ARPEGE
  - Weacast
  - krawler
dependencies:
  - name: kargo
    version: x.x.x
    repository: file://../kargo
maintainers:
  - name: Kalisio
    email: contact@kalisio.com
    url: https://kalisio.com
