# create required Role, RoleBinding and Service account to run the mongo operator instance
#Â Information from https://wiki.ul2i.fr/fr/kubernetes/operator-mongodb
---
{{- if .Values.serviceAccount.create -}}
# ServiceAccount for database
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-database-pods
  labels:
    {{- include "mongodb-operated.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
# ServiceAccount for mongo pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-appdb
  labels:
    {{- include "mongodb-operated.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---
# Role to read secret and modify pod
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-kubernetes-{{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
  - delete
  - get

---
# Bind role and SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-kubernetes-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-kubernetes-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-appdb
{{- end }}