apiVersion: v2
name: kazarr
description: Lightweight service for reading and transforming Zarr data
version: 0.0.1
appVersion: 1.0.0
home: https://github.com/kalisio/kazarr
annotations:
  category: Service
keywords:
  - processing
  - zarr
dependencies:
  - name: kargo
    version: x.x.x
    repository: file://../kargo
maintainers:
  - name: Kalisio
    email: contact@kalisio.com
    url: https://kalisio.com
