apiVersion: v1
kind: Service
metadata:
  name: overpass-api
spec:
  selector:
    app: overpass-api
  ports:
    - name: {{ include "kargo.names.name" . }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort | default .Values.service.port }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  type: ClusterIP
