apiVersion: v2
name: k-vigicrues
description: >-
  A Krawler based service to download data from French flood warning system
  Vigicrues
version: 1.3.1
appVersion: 1.10.1
home: https://github.com/kalisio/k-vigicrues
annotations:
  category: KrawlerJob
keywords:
  - vigicrues
  - krawler
dependencies:
  - name: kargo
    version: x.x.x
    repository: file://../kargo
maintainers:
  - name: Kalisio
    email: contact@kalisio.com
    url: https://kalisio.com
