apiVersion: v2
name: pdfme
description: pdfme
version: 0.0.1
appVersion: 0.0.1
annotations:
  category: application
dependencies:
  - name: kargo
    version: x.x.x
    repository: file://../kargo
maintainers:
  - name: Kalisio
    email: contact@kalisio.com
    url: https://kalisio.com
