apiVersion: v2
name: kfs
description: Kano Features Service
version: 1.0.10
appVersion: 1.4.1
home: https://github.com/kalisio/kfs
annotations:
  category: Service
keywords:
  - kano
  - OGC
  - features
dependencies:
  - name: kargo
    version: x.x.x
    repository: file://../kargo
maintainers:
  - name: Kalisio
    email: contact@kalisio.com
    url: https://kalisio.com
