apiVersion: v2
name: kapture
description: Capture Kano Snapshots as a Service
version: 1.3.4
appVersion: 1.5.3
home: https://github.com/kalisio/kapture
annotations:
  category: Service
keywords:
  - kano
  - capture
dependencies:
  - name: kargo
    version: x.x.x
    repository: file://../kargo
maintainers:
  - name: Kalisio
    email: contact@kalisio.com
    url: https://kalisio.com
