apiVersion: v2
name: weacast-gfs-world-loader
description: A Krawler based service to download GFS world forecast data
version: 1.0.2
appVersion: world-1.11.0
home: https://github.com/weacast/weacast-loader
annotations:
  category: WeacastLoader
keywords:
  - GFS
  - Weacast
  - krawler
dependencies:
  - name: kargo
    version: x.x.x
    repository: file://../kargo
maintainers:
  - name: Kalisio
    email: contact@kalisio.com
    url: https://kalisio.com
